### ISSUE TITLE
Video unavailable. This video is restricted.

### ISSUE THREAD

**Issue by galgofa** [dgalli1/ytm-mpd#1]
Dear dgalli1,

Thank you very mush for this great idea but whatever i tried doesn't  work for me with following error:

ERROR: [youtube] X0dfs5GxHuE: Video unavailable. This video is restricted. Please check the Google Workspace administrator and/or the network administrator restrictions.

Can you please if possible to look to fix it.
Thank you.

**Comment by dgalli1** [comment]
Can you post the full log?
Also, I assume this error happened on this Video?
[X0dfs5GxHuE](https://www.youtube.com/watch?v=X0dfs5GxHuE)


Did you run in docker?

**Comment by galgofa** [comment]
Yes i use docker, the same issue if installed in the system.
Here is the full log of one try:

`[yt-cast-receiver] Player.play(): CNcgu64rgtY @ 0s
Play CNcgu64rgtY at position 0s
Media URL: https://rr6---sn-4vguioxu-5ui6.googlevideo.com/videoplayback?expire=1700870881&ei=geZgZe7ANPu66dsP0puD0Ao&ip=77.49.129.173&id=o-AH3k6UW2xp3YKWahJd92eCPjBUx49Rr5l0FUwyLUamDJ&itag=140&source=youtube&requiressl=yes&mh=-l&mm=31%2C29&mn=sn-4vguioxu-5ui6%2Csn-nv47znee&ms=au%2Crdu&mv=m&mvi=6&pcm2cms=yes&pl=21&initcwndbps=905000&spc=UWF9f3MAU-XJ-AuafeFJpjgn6K-2JSNZ99U8ZjjZ_Q&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=218717080&dur=13514.454&lmt=1658347543337909&mt=1700848865&fvip=4&keepalive=yes&fexp=24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ANLwegAwRAIgZcogugaVEmLSRsW_7VhO-rq6KKurmJVfsBjs5brB40ICICH9NYSO-Kz1CDmD4RoOswDccHOH0lJUoXUzm-_AbM3m&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AM8Gb2swRQIhALXCBOAqG9AcrpvFBf5lvwZA-KlPkjlhTdXxU1shPGJMAiB60OT8nro-Ns59G7UbbJZsCwDGM_iTYgq-Gl2DgY4GTA%3D%3D
/app/node_modules/mpd2/lib/index.js:147
        : this._reject(new MPDError(desc))
                       ^
MPDError: Failed to decode https://rr6---sn-4vguioxu-5ui6.googlevideo.com/videoplayback?expire=1700870881&ei=geZgZe7ANPu66dsP0puD0Ao&ip=77.49.129.173&id=o-AH3k6UW2xp3YKWahJd92eCPjBUx49Rr5l0FUwyLUamDJ&itag=140&source=youtube&requiressl=yes&mh=-l&mm=31%2C29&mn=sn-4vguioxu-5ui6%2Csn-nv47znee&ms=au%2Crdu&mv=m&mvi=6&pcm2cms=yes&pl=21&initcwndbps=905000&spc=UWF9f3MAU-XJ-AuafeFJpjgn6K-2JSNZ99U8ZjjZ_Q&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=218717080&dur=13514.454&lmt=1658347543337909&mt=1700848865&fvip=4&keepalive=yes&fexp=24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ANLwegAwRAIgZcogugaVEmLSRsW_7VhO-rq6KKurmJVfsBjs5brB40ICICH9NYSO-Kz1CDmD4RoOswDccHOH0lJUoXUzm-_AbM3m&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AM8Gb2swRQIhALXCBOAqG9AcrpvFBf5lvwZA-KlPkjlhTdXxU1shPGJMAiB60OT8nro-Ns59G7UbbJZsCwDGM_iTYgq-Gl2DgY4GTA%3D%3D; CURL failed: The requested URL returned error: 403 Forbidden
    at MPDClient._receive (/app/node_modules/mpd2/lib/index.js:147:24)
    at Socket.emit (node:events:511:28)
    at addChunk (node:internal/streams/readable:332:12)
    at readableAddChunk (node:internal/streams/readable:301:11)
    at Readable.push (node:internal/streams/readable:242:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 'UNKNOWN',
  errno: 5,
  cmd_list_num: 0,
  current_command: 'seekcur'
}
Node.js v20.2.0
Creating new renderer: localhost
[yt-cast-receiver] DIAL server listening on port 3000
node:events:489
      throw er; // Unhandled 'error' event
      ^
Error: bind EADDRINUSE 10.10.1.1:50010
    at node:dgram:362:20
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Peer instance at:
    at Socket.onError (/app/node_modules/@patrickkfkan/peer-ssdp/lib/peer-ssdp.js:71:14)
    at Socket.emit (node:events:523:35)
    at node:dgram:364:14
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -98,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: '10.10.1.1',
  port: 50010
}
Node.js v20.2.0
Creating new renderer: localhost
[yt-cast-receiver] Failed to get value for key 'mdxContext.m' in data store: (Error) [node-persist][readFile] .node-persist/storage/cd6fbe44cba81d9d7342a4f6245d4544 does not look like a valid storage file! Error: [node-persist][readFile] .node-persist/storage/cd6fbe44cba81d9d7342a4f6245d4544 does not look like a valid storage file!
    at /app/node_modules/node-persist/src/local-storage.js:316:89
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
[yt-cast-receiver] DIAL server listening on port 3000`

**Comment by dgalli1** [comment]
The Docker containers had a old version of yt-dlp as I didn't update them for half a year. Run docker compose pull and docker compose up again then you should be on the newest version. 

I now rebuilt the image so that it takes the newest version.
If you ever encounter this error again please try to update yt-dlp via the command "yt-dlp --update"

**Comment by dgalli1** [comment]
Also the error repots that the port 3000 is already in use. The dial server can't use another port. So if you have something else that uses this port you will have to close it before running the programm.

**Comment by galgofa** [comment]
Thank you for the update, it works now but for some videos only. Understood it is the same issue with yt-dlp ? 
By the way how i can install in the system without installing MDP (because i have it already running) in order to use yt-dlp installed and updated in the system regularly ?

Now i have flw error:

`Error: Command failed: youtube-dl -f bestaudio[ext=m4a] --get-url "https://www.youtube.com/watch?v=7qxUVTGKp_4"
ERROR: [youtube] 7qxUVTGKp_4: Video unavailable. This video is restricted. Please check the Google Workspace administrator and/or the network administrator restrictions.`

**Comment by dgalli1** [comment]
Weird youtube-dl only gets executed when yt-dlp fails.
And when i run the command my self it works perfectly fine.

Can you run yt-dlp inside of the container and execute 
yt-dlp -f bestaudio[ext=m4a] --get-url "https://www.youtube.com/watch?v=7qxUVTGKp_4" -vvv and post the output here?

Most likely your network has an issue or something similar

**Comment by galgofa** [comment]
there is output:

`yt-dlp -f bestaudio[ext=m4a] --get-url "https://www.youtube.com/watch?v=7qxUVTGKp_4" 
https://rr2---sn-4vguioxu-5ui6.googlevideo.com/videoplayback?expire=1701037199&ei=L3BjZbjcDeWDi9oP1tS96Aw&ip=77.49.129.173&id=o-ADiNLRYoJGrvULqCmTo0DWGV7wQvg2064Egs-EcX5jLE&itag=140&source=youtube&requiressl=yes&mh=WX&mm=31%2C29&mn=sn-4vguioxu-5ui6%2Csn-nv47znee&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=21&initcwndbps=842500&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=100479910&dur=6208.597&lmt=1700939502056440&mt=1701015180&fvip=3&keepalive=yes&fexp=24007246&c=IOS&txp=7308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ANLwegAwRQIgRfz9FDC3NKni1Z8JRXSrbjhhrX1ge7tBpDKSPleez9ECIQDLxrfIdzTxAgB7yKDHN2_Lqp9hsbRinNOJiqvdky4Jnw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AM8Gb2swRgIhAM7vPHWdS1GWuX6E5L0009yAi54eKg2HNt0X5UfUhu1hAiEA46n_muzf4YeY26okWbT8s36bySNzjH-FlgXbPqSz3vs%3D`

**Comment by galgofa** [comment]
Finally seems i found the cause of errors with video not available, it was enabled SafeSearch on the router, after disabling seems most of problem gone, testing all together now. Seems works as it should.
Thank you for support. 

Happy Holidays !
 
My setup is ytm-mpd to MPD to mkchromecast.

**Comment by dgalli1** [comment]
TIL There are routers with integrated SafeSearch :D.

Cool that you could figure it out, and happy holidays to you aswell.
